level = "orange"
targetRoom = orange_1
sprite_index = spr_gate_forest;
bgsprite = spr_gate_farmBG;
title_index = 1;
titlecard_index = 1;
title_music = "event:/music/w2/deserttitle";
group_arr = ["forestgroup"];
msg = "Mission: Orange Battlefield"