targetRoom = cantiere_1;
level = "cantiere";
sprite_index = spr_gate_dungeon;
bgsprite = spr_gate_dungeonBG;
title_index = 3;
titlecard_index = 3;
title_music = "event:/music/w1/dungeontitle";
group_arr = ["dungeongroup"];
msg = "Under Construction"