targetRoom = kungfu_1;
level = "kungfu";
sprite_index = spr_gate_street;
bgsprite = spr_gate_kungfuBG;
title_index = 2;
title_sprite = spr_titlecards_title2;
titlecard_index = 12;
title_music = "event:/music/w4/streettitle";
group_arr = ["kungfugroup"];
msg = "Downtown Madness"